name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: configure
      run: make libs -j4
    - name: make
      run: make
